In [1]:
import numpy as np
import pandas as pd

In [3]:
s = pd.Series([1,46,7,24,np.nan,45,2,5])
s

0 1.0
1 46.0
2 7.0
3 24.0
4 NaN
5 45.0
6 2.0
7 5.0
dtype: float64

In [6]:
daty = pd.date_range("20221209",periods=6)
daty

DatetimeIndex(['2022-12-09', '2022-12-10', '2022-12-11', '2022-12-12',
               '2022-12-13', '2022-12-14'],
              dtype='datetime64[ns]', freq='D')

In [10]:
df = pd.DataFrame(np.random.randn(6,4), index=daty, columns=list("ABCD"))
df

A 
 B 
 C 
 D 
 
 
 
 
 2022-12-09 
 -0.026712 
 0.165084 
 0.518039 
 0.298426 
 
 
 2022-12-10 
 0.612785 
 -1.588146 
 0.472847 
 0.672616 
 
 
 2022-12-11 
 -0.584416 
 0.076918 
 -0.195291 
 0.535971 
 
 
 2022-12-12 
 -0.384783 
 1.057803 
 1.242376 
 0.297427 
 
 
 2022-12-13 
 0.097823 
 -1.070181 
 -0.332997 
 0.792624 
 
 
 2022-12-14 
 -0.582287 
 0.717762 
 0.169826 
 -0.900196

In [11]:
df.head(2)

A 
 B 
 C 
 D 
 
 
 
 
 2022-12-09 
 -0.026712 
 0.165084 
 0.518039 
 0.298426 
 
 
 2022-12-10 
 0.612785 
 -1.588146 
 0.472847 
 0.672616

In [12]:
df.tail(3)

A 
 B 
 C 
 D 
 
 
 
 
 2022-12-12 
 -0.384783 
 1.057803 
 1.242376 
 0.297427 
 
 
 2022-12-13 
 0.097823 
 -1.070181 
 -0.332997 
 0.792624 
 
 
 2022-12-14 
 -0.582287 
 0.717762 
 0.169826 
 -0.900196

In [13]:
df.index

DatetimeIndex(['2022-12-09', '2022-12-10', '2022-12-11', '2022-12-12',
               '2022-12-13', '2022-12-14'],
              dtype='datetime64[ns]', freq='D')

In [14]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [17]:
df2 = df.to_numpy()
print(df2)

[[-0.02671213  0.16508409  0.51803912  0.29842556]
 [ 0.61278507 -1.58814591  0.47284669  0.67261634]
 [-0.58441598  0.07691826 -0.19529083  0.53597093]
 [-0.38478281  1.05780304  1.24237561  0.29742676]
 [ 0.09782345 -1.07018054 -0.33299661  0.79262412]
 [-0.5822869   0.71776189  0.16982606 -0.90019611]]


In [18]:
df.describe()

A 
 B 
 C 
 D 
 
 
 
 
 count 
 6.000000 
 6.000000 
 6.000000 
 6.000000 
 
 
 mean 
 -0.144598 
 -0.106793 
 0.312467 
 0.282811 
 
 
 std 
 0.466689 
 1.026291 
 0.570526 
 0.612521 
 
 
 min 
 -0.584416 
 -1.588146 
 -0.332997 
 -0.900196 
 
 
 25% 
 -0.532911 
 -0.783406 
 -0.104012 
 0.297676 
 
 
 50% 
 -0.205747 
 0.121001 
 0.321336 
 0.417198 
 
 
 75% 
 0.066690 
 0.579592 
 0.506741 
 0.638455 
 
 
 max 
 0.612785 
 1.057803 
 1.242376 
 0.792624

In [19]:
df.T

2022-12-09 
 2022-12-10 
 2022-12-11 
 2022-12-12 
 2022-12-13 
 2022-12-14 
 
 
 
 
 A 
 -0.026712 
 0.612785 
 -0.584416 
 -0.384783 
 0.097823 
 -0.582287 
 
 
 B 
 0.165084 
 -1.588146 
 0.076918 
 1.057803 
 -1.070181 
 0.717762 
 
 
 C 
 0.518039 
 0.472847 
 -0.195291 
 1.242376 
 -0.332997 
 0.169826 
 
 
 D 
 0.298426 
 0.672616 
 0.535971 
 0.297427 
 0.792624 
 -0.900196

In [20]:
df.sort_index(axis=1,ascending=False)

D 
 C 
 B 
 A 
 
 
 
 
 2022-12-09 
 0.298426 
 0.518039 
 0.165084 
 -0.026712 
 
 
 2022-12-10 
 0.672616 
 0.472847 
 -1.588146 
 0.612785 
 
 
 2022-12-11 
 0.535971 
 -0.195291 
 0.076918 
 -0.584416 
 
 
 2022-12-12 
 0.297427 
 1.242376 
 1.057803 
 -0.384783 
 
 
 2022-12-13 
 0.792624 
 -0.332997 
 -1.070181 
 0.097823 
 
 
 2022-12-14 
 -0.900196 
 0.169826 
 0.717762 
 -0.582287

In [21]:
df.sort_values(by="B")

A 
 B 
 C 
 D 
 
 
 
 
 2022-12-10 
 0.612785 
 -1.588146 
 0.472847 
 0.672616 
 
 
 2022-12-13 
 0.097823 
 -1.070181 
 -0.332997 
 0.792624 
 
 
 2022-12-11 
 -0.584416 
 0.076918 
 -0.195291 
 0.535971 
 
 
 2022-12-09 
 -0.026712 
 0.165084 
 0.518039 
 0.298426 
 
 
 2022-12-14 
 -0.582287 
 0.717762 
 0.169826 
 -0.900196 
 
 
 2022-12-12 
 -0.384783 
 1.057803 
 1.242376 
 0.297427

In [22]:
df["A"]

2022-12-09 -0.026712
2022-12-10 0.612785
2022-12-11 -0.584416
2022-12-12 -0.384783
2022-12-13 0.097823
2022-12-14 -0.582287
Freq: D, Name: A, dtype: float64

In [23]:
df[0:3]

A 
 B 
 C 
 D 
 
 
 
 
 2022-12-09 
 -0.026712 
 0.165084 
 0.518039 
 0.298426 
 
 
 2022-12-10 
 0.612785 
 -1.588146 
 0.472847 
 0.672616 
 
 
 2022-12-11 
 -0.584416 
 0.076918 
 -0.195291 
 0.535971

In [24]:
df["20221211":"20221213"]

A 
 B 
 C 
 D 
 
 
 
 
 2022-12-11 
 -0.584416 
 0.076918 
 -0.195291 
 0.535971 
 
 
 2022-12-12 
 -0.384783 
 1.057803 
 1.242376 
 0.297427 
 
 
 2022-12-13 
 0.097823 
 -1.070181 
 -0.332997 
 0.792624

In [26]:
df.loc[daty[0:2]]

A 
 B 
 C 
 D 
 
 
 
 
 2022-12-09 
 -0.026712 
 0.165084 
 0.518039 
 0.298426 
 
 
 2022-12-10 
 0.612785 
 -1.588146 
 0.472847 
 0.672616

In [27]:
df.loc[:,["A","B"]]

A 
 B 
 
 
 
 
 2022-12-09 
 -0.026712 
 0.165084 
 
 
 2022-12-10 
 0.612785 
 -1.588146 
 
 
 2022-12-11 
 -0.584416 
 0.076918 
 
 
 2022-12-12 
 -0.384783 
 1.057803 
 
 
 2022-12-13 
 0.097823 
 -1.070181 
 
 
 2022-12-14 
 -0.582287 
 0.717762

In [28]:
df.loc[daty[0],"D"]

0.29842555517714364

In [29]:
df.iloc[3]

A -0.384783
B 1.057803
C 1.242376
D 0.297427
Name: 2022-12-12 00:00:00, dtype: float64

In [30]:
df.iloc[3:5,0:2]

A 
 B 
 
 
 
 
 2022-12-12 
 -0.384783 
 1.057803 
 
 
 2022-12-13 
 0.097823 
 -1.070181

In [31]:
df.iloc[[1,2,4],[0,2]]

A 
 C 
 
 
 
 
 2022-12-10 
 0.612785 
 0.472847 
 
 
 2022-12-11 
 -0.584416 
 -0.195291 
 
 
 2022-12-13 
 0.097823 
 -0.332997

In [33]:
df[df["A"] >0]

A 
 B 
 C 
 D 
 
 
 
 
 2022-12-10 
 0.612785 
 -1.588146 
 0.472847 
 0.672616 
 
 
 2022-12-13 
 0.097823 
 -1.070181 
 -0.332997 
 0.792624

In [34]:
df[df>0]

A 
 B 
 C 
 D 
 
 
 
 
 2022-12-09 
 NaN 
 0.165084 
 0.518039 
 0.298426 
 
 
 2022-12-10 
 0.612785 
 NaN 
 0.472847 
 0.672616 
 
 
 2022-12-11 
 NaN 
 0.076918 
 NaN 
 0.535971 
 
 
 2022-12-12 
 NaN 
 1.057803 
 1.242376 
 0.297427 
 
 
 2022-12-13 
 0.097823 
 NaN 
 NaN 
 0.792624 
 
 
 2022-12-14 
 NaN 
 0.717762 
 0.169826 
 NaN

In [36]:
df3 = df.copy()
df3["E"] = ["jeden","jeden","trzy","dwa","trzy","jeden"]
df3

A 
 B 
 C 
 D 
 E 
 
 
 
 
 2022-12-09 
 -0.026712 
 0.165084 
 0.518039 
 0.298426 
 jeden 
 
 
 2022-12-10 
 0.612785 
 -1.588146 
 0.472847 
 0.672616 
 jeden 
 
 
 2022-12-11 
 -0.584416 
 0.076918 
 -0.195291 
 0.535971 
 trzy 
 
 
 2022-12-12 
 -0.384783 
 1.057803 
 1.242376 
 0.297427 
 dwa 
 
 
 2022-12-13 
 0.097823 
 -1.070181 
 -0.332997 
 0.792624 
 trzy 
 
 
 2022-12-14 
 -0.582287 
 0.717762 
 0.169826 
 -0.900196 
 jeden

In [39]:
df3[df3["E"].isin(["dwa","trzy"])]

A 
 B 
 C 
 D 
 E 
 
 
 
 
 2022-12-11 
 -0.584416 
 0.076918 
 -0.195291 
 0.535971 
 trzy 
 
 
 2022-12-12 
 -0.384783 
 1.057803 
 1.242376 
 0.297427 
 dwa 
 
 
 2022-12-13 
 0.097823 
 -1.070181 
 -0.332997 
 0.792624 
 trzy